=head1 NQR - Not Quite R - Currently Implemented Functionality

NQR is Copyright (C) 2011 by John W. Emerson and Michael J. Kane.
See F<LICENSE> for licensing details, Artistic License 2.0.

=head3 Core functionality

<- or = for assignment

vectors of integer, float, string

'[' and '[<-' (bracket operator for get/set, atomic only)

Vectorized operators:
+, -, *, /, :, ==, !=, <, <=, >, >=, !

function (definition and calling)

while (for not yet available)

if... then... else

seq, rep, c, paste

str, length

print

which.max, which.min

is.array

% mod is not yet vectorized

# for comments

& | not yet vectorized (and no && or || yet)

=head2 With internals from libRmath

set.seed

rexp

=head2 With internals from GNU Scientific Library (GSL)

NOTE: I can't yet pass integers into GSL, so operations on ResizableIntegerArray
objects will not work yet.

dnorm, pnorm, qnorm

dunif, punif, qunif

max, min

mean, var, sd, cov, cor

order, sort

log, exp



